### ISSUE TITLE
1.16.1 port?

### ISSUE THREAD

**Issue by jinkhya** [ldtteam/Logprot#1]
Hello, some of my friends are having issues on logging on some heavier 1.16 servers and that mod would save them from the frustration of being killed on logging as it can sometimes take 1 to 3 minutes
Do you plan on updating it to 1.16+ ? it'd be really appreciated :)
Thanks in advance.
Jin

**Comment by someaddons** [comment]
updated^^

**Comment by jinkhya** [comment]
awesome thank you !!
