### ISSUE TITLE
Invulnerability when logging in or changing dimensions

### ISSUE THREAD

**Issue by suuty** [ldtteam/Logprot#12]
Players on my Essential server would randomly become invulnerable when logining in or changing dimensions

To Reproduce:
login to world
if invulnerable for ever done
if not
change dimensions

Expected behavior:
not be invulnerable

Version:
3.1

Modlist:
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[MC Dungeons Armors (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcda)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Main Menu Credits (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/main-menu-credits)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Mob Origins (by UltrusBot)](https://www.curseforge.com/minecraft/mc-mods/mob-origins)
[AdvancementInfo (by Giselbaer)](https://www.curseforge.com/minecraft/mc-mods/advancementinfo)
[Runes [Fabric] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/rune-crafting)
[Extra Origins (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/extra-origins)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[OptiGUI (by opekope2)](https://www.curseforge.com/minecraft/mc-mods/optigui)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[e4mc (by skyegreen)](https://www.curseforge.com/minecraft/mc-mods/e4mc)
[Hang Glider [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/hang-glider)
[FastQuit (by KingContaria)](https://www.curseforge.com/minecraft/mc-mods/fastquit)
[Extra Alchemy (by zabi94)](https://www.curseforge.com/minecraft/mc-mods/extra-alchemy)
[Fabrishot (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/fabrishot)
[Inventory Sorting (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Servux (by masady)](https://www.curseforge.com/minecraft/mc-mods/servux)
[FTB Ultimine (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric)
[Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[Better Tridents [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[Handcrafted (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Goblin Traders [Fabric] (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Geode+ [Forge/Fabric] (by YeoXuHang)](https://www.curseforge.com/minecraft/mc-mods/geode-plus)
[Trash Cans (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/trash-cans)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[AntiGhost (by Giselbaer)](https://www.curseforge.com/minecraft/mc-mods/antighost)
[Very Many Players (Fabric) (by ishlandmc)](https://www.curseforge.com/minecraft/mc-mods/vmp-fabric)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Just Enough Breeding (JEBr) (by Christofmeg)](https://www.curseforge.com/minecraft/mc-mods/justenoughbreeding)
[Universal Graves (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/universal-graves)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Things [Fabric] (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/things-fabric)
[Enchanting Infuser [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Menulogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/menulogue)
[FabricSkyBoxes Interop (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/fabricskyboxes-interop)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[FabricSkyboxes (by AMereBagatelle)](https://www.curseforge.com/minecraft/mc-mods/fabricskyboxes)
[FTB Essentials (Forge & Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)
[Better Mount HUD (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Borderless Mining (by comp500)](https://www.curseforge.com/minecraft/mc-mods/borderless-mining)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Simple Fog Control (by Draradech)](https://www.curseforge.com/minecraft/mc-mods/simplefog)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[MiniHUD (by masady)](https://www.curseforge.com/minecraft/mc-mods/minihud)
[Catalogue (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[Capes [Fabric/Forge] (by VictorKohler)](https://www.curseforge.com/minecraft/mc-mods/capes)
[Alternate Origin GUI (by UltrusBot)](https://www.curseforge.com/minecraft/mc-mods/altorigingui)
[Just Enough Painting Previews (JEPP) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/jepp)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Extra Classes - Origins (by proman468)](https://www.curseforge.com/minecraft/mc-mods/extra-classes-origins)
[Item Scroller (by masady)](https://www.curseforge.com/minecraft/mc-mods/item-scroller)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[Mighty Mail (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mighty-mail-fabric)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Origins: Classes (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Puzzle (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/puzzle)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Tweakeroo (by masady)](https://www.curseforge.com/minecraft/mc-mods/tweakeroo)
[Bewitchment (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/bewitchment)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Easy Shulker Boxes [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Universal Enchants (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Spell Engine (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/spell-engine)
[Fadeless (by DerpDerpling)](https://www.curseforge.com/minecraft/mc-mods/fadeless)
[MC Dungeons Artifacts (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdar)
[Cardinal Components API (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Overflowing Bars [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/overflowing-bars)
[Animatica (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/animatica)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
[Origins (Fabric) (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Dark Utilities (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Enhanced Block Entities (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities)
[Spell Power Attributes [Fabric] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/spell-power)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Areas (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/areas)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Cosmetic Armor [FABRIC] (by Apace)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric)
[Framework (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework-fabric)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Immersive Melodies [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-melodies)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Concurrent Chunk Management Engine (Fabric) (by ishlandmc)](https://www.curseforge.com/minecraft/mc-mods/c2me-fabric)
[Just Enough Farmer's Recipes (by Anxxitty__)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-jei-plugin)
[MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)
[Hold That Chunk (by The_TermiGator)](https://www.curseforge.com/minecraft/mc-mods/hold-that-chunk)
[Litematica (by masady)](https://www.curseforge.com/minecraft/mc-mods/litematica)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[AzureLib Armor (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/azurelib-armor)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[More Chat History (by JackFred2)](https://www.curseforge.com/minecraft/mc-mods/more-chat-history)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Wizards (RPG Series) (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/wizards)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[Language Reload (by Jerozgen)](https://www.curseforge.com/minecraft/mc-mods/language-reload)
[River Redux (by Jasmine)](https://www.curseforge.com/minecraft/mc-mods/river-redux)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Trading Post [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[MaLiLib (by masady)](https://www.curseforge.com/minecraft/mc-mods/malilib)
[Hybrid Aquatic (by HybridLabs)](https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Tom's Simple Storage Mod (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[CIT Resewn (by SHsuperCM)](https://www.curseforge.com/minecraft/mc-mods/cit-resewn)
[Better Sodium Video Settings Button (by PiemanDev)](https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button)
[Diagonal Fences [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[TrimsEffects (by lupiiin_)](https://www.curseforge.com/minecraft/mc-mods/trimseffects)
[Bartering Station [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Your Options Shall Be Respected (YOSBR) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/yosbr)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[[FABRIC/QUILT] Disable Custom Worlds Advice (by Nara)](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)

**Comment by someaddons** [comment]
essentials bug, report to them or use a proper server
