### ISSUE TITLE
Nether (The call method_5643 is not cancellable.)

### ISSUE THREAD

**Issue by kittech0** [ldtteam/Logprot#2]
When trying go to nether i get this error (Fabric 1.18.1)
[crash-2022-01-03_22.55.57-server.txt](https://github.com/ldtteam/Logprot/files/7804259/crash-2022-01-03_22.55.57-server.txt)
`The call method_5643 is not cancellable.`

**Comment by someaddons** [comment]
should be fixed in v1.5 :)
