### ISSUE TITLE
LogIn doesn't protect from fall damage

### ISSUE THREAD

**Issue by Laifsyn** [ldtteam/Logprot#3]
Either I messed up somewherein the config, but before I went to troll a friend, I've set myself to spawn at an height which I can die on joining the server. Oh, well. Guess what - I died.

TLDR: You die from fall  damage on loggin

**Comment by someaddons** [comment]
you are damage immune for a certain time or distance after logging in, if either limit is reached the immunity is removed. To see when the immunity gets removed you can turn on the debug config
