### ISSUE TITLE
Protection Time is less than intended

### ISSUE THREAD

**Issue by NielsPilgaard** [ldtteam/Logprot#4]
**Describe the bug**
Players are not protected for the amount of ticks that the config states, they're not even protected for the same duration as the debug.log states that the protection lasts: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4822#issuecomment-1124804404

Note that the player was not moved in the process.

**To Reproduce**
1. Join a server
2. Make sure to take damage on login, somehow
3. See that the player dies before the ticks specified in the logprot config

**Expected behavior**
For the protection to last as long as the config specifies.

**Screenshots**

**Version**
Add the mods version/file name here

**Additional context**

**Comment by someaddons** [comment]
fixed in 1.6

**Comment by NielsPilgaard** [comment]
Thanks!
