### ISSUE TITLE
[1.19] Client crash on creating a new single player world

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Logprot#5]
https://gist.githubusercontent.com/ProsperCraft/8e562629a27e11c2baab1aba7309d928/raw/3c4053b9047147e38d8e36dff0b117fe2faba94e/gistfile1.txt

**Comment by someaddons** [comment]
only works on the older forge

**Comment by ProsperCraft** [comment]
No worries, removed it until you update.

I can be patient.

**Comment by someaddons** [comment]
fixed in 1.7
