### ISSUE TITLE
Login Protection Being Added But No Effect Occurs

### ISSUE THREAD

**Issue by AutoRunFail** [ldtteam/Logprot#7]
I have Login Protection on a hosted server for **1.19.2 on Fabric**. 

I took a screenshot of the relevant console part, but basically, I set the login protection to be 10000 ticks to test it, and it writes that it has applied the protection, but the player spawning in immediately dies from a pillager upon logging in. They haven't moved or done anything to go outside the range - it seems like the effect is just not working at all. 

We also noticed that protection was added and then immediately removed upon a respawn. Presumably this is because the code is looking for a spawn rather than a connection, we just thought we would mention it in case that is unintended or if that is interfering with the regular login protection. 

We have tried adjusting the settings in the config, spawning in different areas, etc. Nothing seems to work. 

We are playing modded Fabric server with a Fabric Loader version **0.14.10**, and Fabric API of **0.69.0**.
The Minecraft version is **1.19.2**. 
We are using Login Protection with the file name **logprot-fabric-1.19-1.9.jar** . 

Let me know if you need any more information. 
![Death Screen](https://user-images.githubusercontent.com/105956312/210018935-d63ef4f2-58cc-42b9-a551-7ecefa5192e0.png)
![Death Log 2](https://user-images.githubusercontent.com/105956312/210018940-b5b8480c-8043-4fa7-8a25-1370002d9e68.png)

**Comment by someaddons** [comment]
fixed in 2.0
